# Generated by Django 5.0.2 on 2024-03-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
