# Generated by Django 5.0.2 on 2024-03-02 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customusermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
