# Generated by Django 5.0.2 on 2024-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customusermodel_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
