# Generated by Django 5.0.2 on 2024-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customusermodel_is_active_otpemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
